baseURL = "http://blog.prdx.me"
title = "Blogname"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = " "

theme = "minimo"

disqusShortname = "prdx"
googleAnalytics = "UA-115930587-1"

Paginate = 2
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

ignoreFiles = [".swo$"]

[params.info]
description = "this is a test blog desc"
title404 = "Nothing's here!"

[params.sidebar]
enable = false
sticky = false


[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Arsh"
startYear = ""
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = true
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["all"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
# codepen = ""
email = "contact@example.com"
# facebook = ""
github = "arsh23/blog"
# instagram = ""
# linkedin = ""
twitter = "oddanomaly"
# telegram = ""
# google_scholar = ""

[params.social.config]
platforms = ["email","twitter","github"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
